### ISSUE TITLE
make build_network on macOS 10.13.4

### ISSUE THREAD

**Issue by gharibshaha** [JSybrandt/MOLIERE#4]
Hi 
After making flann I went to build_network directory to make it but I ran into this error
"Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      toAscii(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in ccXhbGuk.o
  "_iconv_open", referenced from:
      toAscii(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in ccXhbGuk.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [bin/parseXML] Error 1"

is there any thought ?
Thank you

**Comment by JSybrandt** [comment]
I'm going to take a look into this. I don't own a macbook, so it might take me a little bit to get setup.
As a warning, the network construction process requires about 250Gb of RAM, while the query process tends to take about 12Gb - 40Gb.

In the meantime, the results of the network construction process are available online, so if your main concern is running queries, I an help you get that setup faster.

**Comment by gharibshaha** [comment]
Thank you for the information and consideration. I want to build the network on a kind of data with a similar structure on a different domain. So basically I need to run the build network module and cannot use the pre-made network.

Thank you

**Comment by JSybrandt** [comment]
Okay I'm looking around a little bit more and I think your issue is the same as the one found here (https://stackoverflow.com/questions/4546484/iconv-routines-get-translated-to-libiconv-names-and-fail-to-link-on-os-x)
I think one solution may be to change your gcc (if you havn't changed the default gcc already).
Mac gcc is an alias to clang, and it looks like iconv doesn't link properly.

**Comment by JSybrandt** [comment]
As a note, if you are note using the medical parsing functions of the build_network script. then you won't need the parseXML function anyways.
That is just used to extract titles and abstracts from MEDLINE.

If you have your own text, you should be able to skip through a lot of the initial phases.

In fact, I should have my code support that.
